[POC] Validate contract with Sourcify
walnuthq/op-scan pull request #25
Opened 2024-06-23 19:54 UTC by matthieuauger

This PR is a proof of concept for Sourcify integration. https://github.com/walnuthq/op-scan/issues/9

# Proof of validation
For my testing I deployed a simple [ERC20 contract](https://github.com/matthieuauger/kakarot-test-contract). Here is the 
[output from Hardhat](https://github.com/user-attachments/files/15945756/2aac4054f48cad48f1c32754b09cbbc8.json) that we can upload to sourcify to validate the contract.

<img width="891" alt="image" src="https://github.com/walnuthq/op-scan/assets/1172099/3beba051-fa30-42cb-932f-b0e874ef543a">
<img width="914" alt="image" src="https://github.com/walnuthq/op-scan/assets/1172099/5db2fbb8-bf40-4fc3-92c6-a7268dd78b6e">

# Changes that need to be made to fully implement the feature

- use chainId from global configuration
- see how we handle [partial matches](https://docs.sourcify.dev/docs/full-vs-partial-match/#partial-matches)
- handle [solc-json](https://docs.sourcify.dev/docs/api/#/Stateless%20Verification/post_verify_solc_json)
- move some of the logic to external files
- better error management

2024-06-24 05:15 UTC, mazurroman commented
Would be good to check if it also works for brand new chains.

@saimeunt maybe you could give it a spin with your local OP Stack chain?

2024-06-25 06:44 UTC, matthieuauger commented
Thinking about your comment, I need to perform deeper investigation. Sourcify has a bunch of supported chains, OP for example, but this is a manually maintained list.

There are three options that could be explored if we want to support any chain deployed on the superchain:
- manually adding it new chains to Sourcify: there is an existing process for that. If the process is quick and easy it would be the simplest way
- looking at Sourcify code to see if a more permissionless approach can be implemented, technically they should be able to support any EVM chain, I'm wondering why this is a manual step
- hosting our own validation server that support chains on superchain 

First thing would be to test the first option. Do we have a test OP Stack deployed and running somewhere besides localhost?

2024-06-25 10:07 UTC, saimeunt commented
@matthieuauger Hi Matthieu, thank you for your POC, it looks like integrating with sourcify to verify contracts and display the source code as well as fetching the correct ABI is totally feasible and quite easy to setup as they're doing all the heavy lifting.

At the moment we're focused on running the explorer locally and to our best knowledge, verifying contracts on your own devnet, besides testing and developing the feature for future usage on a real self-hosted explorer in production is of little use.

We discussed with @mazurroman how we envision the architecture for going to production with sourcify and we would probably go with hosting our own version of sourcify-server along with the explorer and the indexer as part of a SaaS / Rollup as a Service approach.
As far as the manual process is concerned, I think it's simply to discard obscure, short-lived chains from being added/indexed by their service, just like you can request adding your chain on say [viem](https://github.com/wevm/viem/blob/main/src/chains/definitions).

So I think the scope of this issue is already addressed with your POC and you don't need to go deeper.
I'll keep this open until the end of the hack as this is not top-priority and we'll merge your work ASAP to keep it as reference for later, thank you for your contribution!

2024-06-25 11:52 UTC, matthieuauger commented
Alright 👌

2024-07-01 12:44 UTC, saimeunt requested changes
@matthieuauger Thanks for the POC, we'll merge this as is to keep a reference implementation when contract verification is on scope again.
Can you fix the conflict with the lockfile please?

2024-07-01 12:53 UTC, matthieuauger commented
@saimeunt that's good 👍

2024-07-01 12:53 UTC, saimeunt approved these changes

2024-07-01 12:54 UTC, merged