created the block details page
walnuthq/op-scan pull request #30
Opened 2024-06-26 04:16 UTC by Dprof-in-tech

closes #7 

Here is what the block details page looks like 

![image](https://github.com/walnuthq/op-scan/assets/116242877/607e08c7-50f1-4467-91db-16d37b97ee41)

2024-06-27 09:23 UTC, saimeunt requested changes
@Dprof-in-tech please carefully review and make the requested changes to get this merged.

2024-06-27 09:23 UTC, saimeunt commented on pnpm-lock.yaml
Don't commit your pnpm-lock.yaml as it's been generated with an outdated pnpm version.
Checkout the version from main instead.

2024-06-27 09:23 UTC, saimeunt commented on src/app/block/[block]/page.tsx
> +const client = createPublicClient({
We already define a `l2PublicClient` in `@/lib/chains.ts`, use this instead.

2024-06-27 09:23 UTC, saimeunt commented on src/app/block/[block]/page.tsx
> +function formatTimestamp(timestamp: number): string {
Use the `formatTimestamp` from `@/lib/utils.ts`.

2024-06-27 09:23 UTC, saimeunt commented on src/app/block/[block]/page.tsx
> +                <dt className="text-sm font-medium ">Block Height:  </dt>
Use `DescriptionListItem` from `@/components/lib/description-list-item.tsx` to ensure consistency between pages.

2024-06-27 09:23 UTC, saimeunt commented on src/app/block/[block]/page.tsx
> +              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
Remove baseFeePerGas item as it's not deemed necessary by Etherscan.

2024-06-27 09:23 UTC, saimeunt commented on src/app/block/[block]/page.tsx
> +                <dd className="mt-1 text-sm  sm:mt-0 sm:col-span-2">{blockData.gasUsed.toString()}</dd>
Format `gasUsed` using a NumberFormatter and en-US locale so we have commas.
See some examples here: https://github.com/walnuthq/op-scan/blob/main/src/lib/utils.ts

Also, we need the percentage of gas used over gas limit displayed in parenthesis.

2024-06-27 09:23 UTC, saimeunt commented on src/app/block/[block]/page.tsx
> +                <dd className="mt-1 text-sm sm:mt-0 sm:col-span-2">{blockData.gasLimit.toString()}</dd>
Again, this should be formatted using NumberFormatter.

2024-06-28 03:29 UTC, Dprof-in-tech commented
all changes has been made as requested
![image](https://github.com/walnuthq/op-scan/assets/116242877/7c6f4b2d-0a26-472e-b2b3-0c4232f18e28)

2024-06-28 03:32 UTC, closed without merging