Feat/contract page transactions
walnuthq/op-scan pull request #65
Opened 2024-08-04 22:17 UTC by Benjtalkshow

close #41
## Contract page transactions
This PR implements a new feature to fetch and display transactions specific to a given contract address.
 
###  New Features
- Introduced `fetchTransactionsData` function to retrieve transactions from the database
- Created `AddressTransactions` component to display transaction data
- Implemented filtering for valid transactions (those with receipts)
- Added error handling for transaction processing to improve reliability
- Ensured accurate counting of valid transactions

### Technical Details

- Utilizes Prisma for database interactions
- Implements Promise.all for efficient asynchronous processing of transactions
- Limits displayed transactions to 25 for performance, while showing the total count of valid transactions
- Uses the existing `TxsTable` component for consistent transaction display across the application

###  Testing

- Tested with various Ethereum addresses to ensure correct fetching and display of transactions
- Verified error handling by simulating failed transaction processing
- Confirmed accurate counting of valid transactions

### Component Refactoring
- Moved and renamed the latest-transaction-table and its row component to components/lib for better organization and clarity.

### Performance Considerations
- The function fetches all associated transactions before processing, which may impact performance for addresses with a large number of transactions
- Future optimization could include pagination.

Here is the preview below (Desktop)
![image](https://github.com/user-attachments/assets/ccca98d2-89e8-4a02-ac80-2fe2242c9663)
Here is the preview below (Desktop)
![image](https://github.com/user-attachments/assets/b37411d3-10bc-48f2-9afb-f7dcc85d58fb)

I await any corrections. Thanks

2024-08-05 15:10 UTC, saimeunt requested changes
@Benjtalkshow you're almost there, please make the requested changes and we'll merge this!

2024-08-05 15:10 UTC, saimeunt commented on src/components/pages/address/address-transactions.tsx
> +const TRANSACTION_LIMIT = 25;
Use `process.env.NEXT_PUBLIC_TXS_PER_PAGE` instead.

2024-08-05 15:10 UTC, saimeunt commented on src/components/pages/address/address-transactions.tsx
> +        { from: { contains: address } },
I'm curious why is this needed, can't we use `from: address` directly?
If the addresses do not match exactly maybe this is because we store checksum address in the database and the address in the URL should be formatted using viem `getAddress`.

2024-08-05 15:10 UTC, saimeunt commented on src/components/pages/address/address-transactions.tsx
> +    },
You're missing a `take: Number(process.env.NEXT_PUBLIC_TXS_PER_PAGE)` here to only fetch the correct amount of transactions.

2024-08-05 15:10 UTC, saimeunt commented on src/components/pages/address/address-transactions.tsx
> +    totalCount: filteredValidTransactions.length,
Total count should be computed in a separate prisma query, see https://www.prisma.io/docs/orm/reference/prisma-client-reference#count

2024-08-05 15:10 UTC, saimeunt commented on src/components/pages/address/address-transactions.tsx
> +        Latest {transactions.length >= TRANSACTION_LIMIT ? TRANSACTION_LIMIT : transactions.length} from a total of {totalCount} valid transactions
You can safely use transactions.length here after making the rest of the requested changes.

2024-08-06 09:54 UTC, Benjtalkshow commented
@saimeunt 

The following changes have been implemented:

- Replaced `TRANSACTION_LIMIT` constant with `process.env.NEXT_PUBLIC_TXS_PER_PAGE` for consistency.
- Simplified the address query by using the checksum address directly, assuming addresses are stored in checksum format in the database.
- Added a take limit to the transaction query to fetch only the required number of transactions.
- Separated the total count query for better performance, using Prisma's count method.
- Updated the component to use `transactions.length` for displaying the number of fetched transactions.

The component now correctly displays the latest transactions for a given address, with accurate count information.
Please review these changes and let me know if any further adjustments are needed.

2024-08-09 06:43 UTC, saimeunt approved these changes

2024-08-09 06:43 UTC, merged